// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdikeheirlyosvkwsevd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkaWtlaGVpcmx5b3N2a3dzZXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzI2ODAsImV4cCI6MjA2MDY0ODY4MH0.mbnqnMhEJ_5qXszK33VqdjyRctPMzXUf7rNMtli37Uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);